//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDAO.Usuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class instalaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public instalaciones()
        {
            this.pistas = new HashSet<pistas>();
        }
    
        public string nombre { get; set; }
        public string direccion { get; set; }
        public bool operativa { get; set; }
        public int id_horario { get; set; }
        public int id_instalacion { get; set; }
        public byte[] imagen { get; set; }
    
        public virtual horarios horarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pistas> pistas { get; set; }
    }
}
