//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDAO.Usuario
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDReservasEntities : DbContext
    {
        public BDReservasEntities()
            : base("name=BDReservasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<estados> estados { get; set; }
        public virtual DbSet<horarios> horarios { get; set; }
        public virtual DbSet<instalaciones> instalaciones { get; set; }
        public virtual DbSet<perfiles> perfiles { get; set; }
        public virtual DbSet<pistas> pistas { get; set; }
        public virtual DbSet<reservas> reservas { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tarifas> tarifas { get; set; }
        public virtual DbSet<tipo_pista> tipo_pista { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    
        public virtual int PA_DELETE_USUARIO(Nullable<int> iD, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_DELETE_USUARIO", iDParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_INSERT_PERFIL(string perfil, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var perfilParameter = perfil != null ?
                new ObjectParameter("perfil", perfil) :
                new ObjectParameter("perfil", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_INSERT_PERFIL", perfilParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_INSERT_USUARIO(string nombre, string apellido1, string apellido2, string dni, string email, string password, Nullable<int> id_perfil, byte[] imagen, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("apellido1", apellido1) :
                new ObjectParameter("apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("apellido2", apellido2) :
                new ObjectParameter("apellido2", typeof(string));
    
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var id_perfilParameter = id_perfil.HasValue ?
                new ObjectParameter("id_perfil", id_perfil) :
                new ObjectParameter("id_perfil", typeof(int));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("imagen", imagen) :
                new ObjectParameter("imagen", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_INSERT_USUARIO", nombreParameter, apellido1Parameter, apellido2Parameter, dniParameter, emailParameter, passwordParameter, id_perfilParameter, imagenParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_LOGIN(string email, string password, ObjectParameter iD, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_LOGIN", emailParameter, passwordParameter, iD, rETCODE, mENSAJE);
        }
    }
}
