//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDAO.Usuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class pistas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pistas()
        {
            this.reservas = new HashSet<reservas>();
        }
    
        public string nombre { get; set; }
        public int id_tipo_pista { get; set; }
        public int id_instalacion { get; set; }
        public Nullable<bool> operativa { get; set; }
        public int id_pista { get; set; }
    
        public virtual instalaciones instalaciones { get; set; }
        public virtual tipo_pista tipo_pista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservas> reservas { get; set; }
    }
}
