//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDAO.Usuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservas
    {
        public System.DateTime fecha { get; set; }
        public System.TimeSpan h_ini { get; set; }
        public System.TimeSpan h_fin { get; set; }
        public int id_pista { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public int id_estado { get; set; }
        public int id_reserva { get; set; }
    
        public virtual estados estados { get; set; }
        public virtual pistas pistas { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
